kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-pv-volume
  labels:
    type: local
    app: mongodb
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Set to the required size (5Gi in this case)
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '/mnt/mongodb'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pv-claim
  labels:
    app: mongodb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi # Set to the required size (5Gi in this case)
