apiVersion: apps/v1
kind: Deployment
metadata:
  name: nft-vr-service
  labels:
    app: nft-vr-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nft-vr-service
  template:
    metadata:
      labels:
        app: nft-vr-service
    spec:
      containers:
        - name: nft-vr-service
          image: robadrinacr1.azurecr.io/nft-vr-service:latest
          ports:
            - containerPort: 3002
          imagePullPolicy: Always
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: nft-vr-service-configmap
                  key: server_port
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: nft-vr-service-configmap
                  key: cors_origin
            - name: MONGO_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: nft-vr-service-secret
                  key: connection_string
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: nft-vr-service-secret
                  key: cloud_name
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: nft-vr-service-secret
                  key: api_key
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: nft-vr-service-secret
                  key: api_secret
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: nft-vr-service-secret
                  key: token_secret
            - name: ACCESS_TOKEN_EXPIRY
              valueFrom:
                secretKeyRef:
                  name: nft-vr-service-secret
                  key: token_expiry
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: nft-vr-service-secret
                  key: refresh_token_secret
            - name: REFRESH_TOKEN_EXPIRY
              valueFrom:
                secretKeyRef:
                  name: nft-vr-service-secret
                  key: refresh_token_expiry


---
apiVersion: v1
kind: Service
metadata:
  name: nft-vr-service
spec:
  selector:
    app: nft-vr-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
