apiVersion: v1
kind: ConfigMap
metadata:
  name: nft-vr-service-configmap
data:
  server_port: '3002'
  cors_origin: '*'
---
apiVersion: v1
kind: Secret
metadata:
  name: nft-vr-service-secret
type: Opaque
data:
  connection_string: bW9uZ29kYjovL21vbmdvZGItc2VydmljZToyNzAxNy9uZnR2cmJhY2tlbmQx
  cloud_name: aXRhY2hpdnJuZnQ=
  api_key: NDk1MzIxMTY4NjgzNDk1
  api_secret: M3JxTmNaRWdGM1JjYkpIZDJHVDlYdElYdjlr
  token_secret: dGhpc2lzZm9yYWNjZXNzdG9rZW5zZWNyZXQ=
  token_expiry: MWQ=
  refresh_token_secret: dGhpc2lzZm9ycmVmcmVzaHRva2Vuc2VjcmV0
  refresh_token_expiry: MTBk
